import { WordSet } from '@/types'

export const adjectives: WordSet = {
  id: 'adjectives',
  name: {
    es: 'Adjetivos',
    en: 'Adjectives',
    ru: 'Прилагательные',
  },
  words: [
    { en: 'Good', es: 'Bueno', ru: 'Хороший' },
    { en: 'Bad', es: 'Malo', ru: 'Плохой' },
    { en: 'New', es: 'Nuevo', ru: 'Новый' },
    { en: 'Old', es: 'Viejo', ru: 'Старый' },
    { en: 'Young', es: 'Joven', ru: 'Молодой' },
    { en: 'Big', es: 'Grande', ru: 'Большой' },
    { en: 'Little', es: 'Pequeño', ru: 'Маленький' },
    { en: 'Long', es: 'Largo', ru: 'Длинный' },
    { en: 'Short', es: 'Corto', ru: 'Короткий' },
    { en: 'High', es: 'Alto', ru: 'Высокий' },
    { en: 'Low', es: 'Bajo', ru: 'Низкий' },
    { en: 'Wide', es: 'Ancho', ru: 'Широкий' },
    { ru: 'Узкий', en: 'Narrow', es: 'Estrecho' },
    { en: 'Easy', es: 'Fácil', ru: 'Лёгкий' },
    { es: 'Difícil', ru: 'Трудный', en: 'Difficult' },
    { ru: 'Важный', en: 'Important', es: 'Importante' },
    { ru: 'Разный', en: 'Different', es: 'Diferente' },
    { en: 'Same', es: 'Mismo', ru: 'Одинаковый' },
    { en: 'Right', es: 'Correcto', ru: 'Правильный' },
    { en: 'Wrong', es: 'Incorrecto', ru: 'Неправильный' },
    { en: 'True', ru: 'Верный', es: 'Verdadero' },
    { en: 'False', es: 'Falso', ru: 'Ложный' },
    { en: 'First', ru: 'Первый', es: 'Primero' },
    { en: 'Last', es: 'Último', ru: 'Последний' },
    { en: 'Next', es: 'Siguiente', ru: 'Следующий' },
    { en: 'Early', ru: 'Ранний', es: 'Temprano' },
    { en: 'Late', es: 'Tarde', ru: 'Поздний' },
    { en: 'Great', ru: 'Отличный', es: 'Excelente' },
    { es: 'Hermoso', ru: 'Красивый', en: 'Beautiful' },
    { es: 'Feo', en: 'Ugly', ru: 'Некрасивый' },
    { en: 'Happy', es: 'Feliz', ru: 'Счастливый' },
    { en: 'Sad', es: 'Triste', ru: 'Грустный' },
    { ru: 'Злой', en: 'Angry', es: 'Enojado' },
    { en: 'Calm', es: 'Tranquilo', ru: 'Спокойный' },
    { en: 'Strong', es: 'Fuerte', ru: 'Сильный' },
    { en: 'Weak', es: 'Débil', ru: 'Слабый' },
    { en: 'Fast', es: 'Rápido', ru: 'Быстрый' },
    { en: 'Slow', es: 'Lento', ru: 'Медленный' },
    { en: 'Hot', ru: 'Горячий', es: 'Caliente' },
    { en: 'Cold', es: 'Frío', ru: 'Холодный' },
    { en: 'Warm', es: 'Cálido', ru: 'Тёплый' },
    { en: 'Cool', es: 'Fresco', ru: 'Прохладный' },
    { en: 'Dark', es: 'Oscuro', ru: 'Тёмный' },
    { en: 'Light', es: 'Claro', ru: 'Светлый' },
    { en: 'Clean', es: 'Limpio', ru: 'Чистый' },
    { en: 'Dirty', es: 'Sucio', ru: 'Грязный' },
    { en: 'Full', es: 'Lleno', ru: 'Полный' },
    { en: 'Empty', es: 'Vacío', ru: 'Пустой' },
    { en: 'Open', es: 'Abierto', ru: 'Открытый' },
    { en: 'Closed', es: 'Cerrado', ru: 'Закрытый' },
    { en: 'Free', es: 'Libre', ru: 'Свободный' },
    { en: 'Busy', es: 'Ocupado', ru: 'Занятый' },
    { en: 'Rich', es: 'Rico', ru: 'Богатый' },
    { en: 'Poor', es: 'Pobre', ru: 'Бедный' },
    { en: 'Cheap', es: 'Barato', ru: 'Дешёвый' },
    { es: 'Caro', ru: 'Дорогой', en: 'Expensive' },
    { en: 'Near', es: 'Cercano', ru: 'Близкий' },
    { en: 'Far', es: 'Lejano', ru: 'Далёкий' },
    { en: 'Real', es: 'Real', ru: 'Реальный' },
    { en: 'Main', ru: 'Главный', es: 'Principal' },
    { en: 'Public', es: 'Público', ru: 'Общественный' },
    { en: 'Private', es: 'Privado', ru: 'Частный' },
    { es: 'Posible', en: 'Possible', ru: 'Возможный' },
    { es: 'Imposible', en: 'Impossible', ru: 'Невозможный' },
    { en: 'Ready', es: 'Listo', ru: 'Готовый' },
    { es: 'Útil', en: 'Useful', ru: 'Полезный' },
    { es: 'Inútil', en: 'Useless', ru: 'Бесполезный' },
    { en: 'Safe', es: 'Seguro', ru: 'Безопасный' },
    { ru: 'Опасный', en: 'Dangerous', es: 'Peligroso' },
    { en: 'Healthy', ru: 'Здоровый', es: 'Saludable' },
    { en: 'Sick', es: 'Enfermo', ru: 'Больной' },
    { en: 'Simple', es: 'Simple', ru: 'Простой' },
    { en: 'Complex', ru: 'Сложный', es: 'Complejo' },
    { es: 'Común', en: 'Common', ru: 'Обычный' },
    { en: 'Special', es: 'Especial', ru: 'Особенный' },
    { ru: 'Интересный', en: 'Interesting', es: 'Interesante' },
    { en: 'Boring', ru: 'Скучный', es: 'Aburrido' },
    { en: 'Famous', es: 'Famoso', ru: 'Известный' },
    { en: 'Popular', es: 'Popular', ru: 'Популярный' },
    { en: 'Local', es: 'Local', ru: 'Местный' },
    { en: 'International', es: 'Internacional', ru: 'Международный' },
    { en: 'Human', es: 'Humano', ru: 'Человеческий' },
    { en: 'Social', es: 'Social', ru: 'Социальный' },
    { es: 'Político', en: 'Political', ru: 'Политический' },
    { en: 'Economic', es: 'Económico', ru: 'Экономический' },
    { en: 'Natural', es: 'Natural', ru: 'Естественный' },
    { es: 'Físico', en: 'Physical', ru: 'Физический' },
    { en: 'Mental', es: 'Mental', ru: 'Умственный' },
    { ru: 'Личный', en: 'Personal', es: 'Personal' },
    { ru: 'Общий', en: 'General', es: 'General' },
    { en: 'Necessary', es: 'Necesario', ru: 'Необходимый' },
    { en: 'Modern', es: 'Moderno', ru: 'Современный' },
    { es: 'Serio', en: 'Serious', ru: 'Серьёзный' },
    { en: 'Clear', ru: 'Ясный', es: 'Transparente' },
    { en: 'Deep', es: 'Profundo', ru: 'Глубокий' },
    { en: 'Heavy', es: 'Pesado', ru: 'Тяжёлый' },
    { en: 'Soft', es: 'Suave', ru: 'Мягкий' },
    { en: 'Hard', es: 'Duro', ru: 'Твёрдый' },
    { en: 'Fresh', ru: 'Свежий', es: 'Reciente' },
    { en: 'Quiet', ru: 'Тихий', es: 'Silencioso' },
  ],
}
