import { WordSet } from '@/types'

export const nouns: WordSet = {
  id: 'nouns',
  name: {
    en: 'Nouns',
    es: 'Sustantivos',
    ru: 'Существительные',
  },
  words: [
    { en: 'Time', ru: 'Время', es: 'Tiempo' },
    { es: 'Año', ru: 'Год', en: 'Year' },
    { ru: 'Люди', es: 'Gente', en: 'People' },
    { en: 'Way', ru: 'Путь', es: 'Camino' },
    { en: 'Day', es: 'Día', ru: 'День' },
    { en: 'Man', es: 'Hombre', ru: 'Мужчина' },
    { es: 'Cosa', ru: 'Вещь', en: 'Thing' },
    { en: 'Woman', es: 'Mujer', ru: 'Женщина' },
    { en: 'Life', es: 'Vida', ru: 'Жизнь' },
    { es: 'Niño', en: 'Child', ru: 'Ребёнок' },
    { ru: 'Мир', en: 'World', es: 'Mundo' },
    { ru: 'Школа', en: 'School', es: 'Escuela' },
    { en: 'State', es: 'Estado', ru: 'Государство' },
    { ru: 'Семья', en: 'Family', es: 'Familia' },
    { en: 'Student', ru: 'Студент', es: 'Estudiante' },
    { en: 'Group', es: 'Grupo', ru: 'Группа' },
    { es: 'País', ru: 'Страна', en: 'Country' },
    { en: 'Problem', es: 'Problema', ru: 'Проблема' },
    { en: 'Hand', es: 'Mano', ru: 'Рука' },
    { en: 'Part', es: 'Parte', ru: 'Часть' },
    { en: 'Place', es: 'Lugar', ru: 'Место' },
    { en: 'Case', es: 'Caso', ru: 'Случай' },
    { en: 'Week', es: 'Semana', ru: 'Неделя' },
    { en: 'Company', es: 'Empresa', ru: 'Компания' },
    { en: 'System', es: 'Sistema', ru: 'Система' },
    { en: 'Program', es: 'Programa', ru: 'Программа' },
    { ru: 'Вопрос', en: 'Question', es: 'Pregunta' },
    { en: 'Work', ru: 'Работа', es: 'Trabajo' },
    { es: 'Gobierno', en: 'Government', ru: 'Правительство' },
    { ru: 'Число', en: 'Number', es: 'Número' },
    { ru: 'Ночь', en: 'Night', es: 'Noche' },
    { en: 'Point', es: 'Punto', ru: 'Точка' },
    { ru: 'Дом', es: 'Casa', en: 'House' },
    { es: 'Agua', ru: 'Вода', en: 'Water' },
    { en: 'Room', ru: 'Комната', es: 'Habitación' },
    { ru: 'Мать', es: 'Madre', en: 'Mother' },
    { en: 'Area', es: 'Área', ru: 'Область' },
    { en: 'Money', es: 'Dinero', ru: 'Деньги' },
    { en: 'History', ru: 'История', es: 'Historia' },
    { en: 'Fact', ru: 'Факт', es: 'Hecho' },
    { es: 'Mes', en: 'Month', ru: 'Месяц' },
    { en: 'Book', es: 'Libro', ru: 'Книга' },
    { en: 'Eye', es: 'Ojo', ru: 'Глаз' },
    { ru: 'Офис', en: 'Office', es: 'Oficina' },
    { en: 'Word', ru: 'Слово', es: 'Palabra' },
    { ru: 'Бизнес', es: 'Negocio', en: 'Business' },
    { es: 'Tema', ru: 'Тема', en: 'Topic' },
    { en: 'Side', es: 'Lado', ru: 'Сторона' },
    { ru: 'Вид', en: 'Kind', es: 'Tipo' },
    { en: 'Head', es: 'Cabeza', ru: 'Голова' },
    { ru: 'Услуга', en: 'Service', es: 'Servicio' },
    { ru: 'Друг', es: 'Amigo', en: 'Friend' },
    { ru: 'Отец', es: 'Padre', en: 'Father' },
    { en: 'Power', es: 'Poder', ru: 'Власть' },
    { ru: 'Час', en: 'Hour', es: 'Hora' },
    { en: 'Game', ru: 'Игра', es: 'Juego' },
    { en: 'Line', es: 'Línea', ru: 'Линия' },
    { en: 'End', es: 'Fin', ru: 'Конец' },
    { en: 'Member', es: 'Miembro', ru: 'Участник' },
    { en: 'Law', es: 'Ley', ru: 'Закон' },
    { en: 'Car', es: 'Coche', ru: 'Машина' },
    { en: 'City', ru: 'Город', es: 'Ciudad' },
    { en: 'Community', es: 'Comunidad', ru: 'Сообщество' },
    { ru: 'Имя', en: 'Name', es: 'Nombre' },
    { en: 'Team', es: 'Equipo', ru: 'Команда' },
    { en: 'Minute', es: 'Minuto', ru: 'Минута' },
    { en: 'Idea', es: 'Idea', ru: 'Идея' },
    { en: 'Body', ru: 'Тело', es: 'Cuerpo' },
    { ru: 'Информация', en: 'Information', es: 'Información' },
    { en: 'Back', ru: 'Спина', es: 'Espalda' },
    { en: 'Relative', es: 'Pariente', ru: 'Родственник' },
    { en: 'Face', es: 'Cara', ru: 'Лицо' },
    { en: 'Door', ru: 'Дверь', es: 'Puerta' },
    { es: 'Salud', en: 'Health', ru: 'Здоровье' },
    { en: 'Person', es: 'Persona', ru: 'Человек' },
    { en: 'Art', es: 'Arte', ru: 'Искусство' },
    { en: 'War', ru: 'Война', es: 'Guerra' },
    { en: 'Party', es: 'Fiesta', ru: 'Вечеринка' },
    { en: 'Result', es: 'Resultado', ru: 'Результат' },
    { en: 'Change', es: 'Cambio', ru: 'Изменение' },
    { ru: 'Утро', es: 'Mañana', en: 'Morning' },
    { es: 'Razón', en: 'Reason', ru: 'Причина' },
    { en: 'Research', ru: 'Исследование', es: 'Investigación' },
    { en: 'Girl', es: 'Niña', ru: 'Девочка' },
    { en: 'Boy', es: 'Chico', ru: 'Мальчик' },
    { en: 'Moment', ru: 'Момент', es: 'Momento' },
    { en: 'Air', es: 'Aire', ru: 'Воздух' },
    { en: 'Teacher', ru: 'Учитель', es: 'Profesor' },
    { ru: 'Сила', en: 'Force', es: 'Fuerza' },
    { en: 'Education', es: 'Educación', ru: 'Образование' },
    { es: 'Pie', en: 'Foot', ru: 'Стопа' },
    { en: 'Age', es: 'Edad', ru: 'Возраст' },
    { en: 'Policy', es: 'Política', ru: 'Политика' },
    { en: 'Process', es: 'Proceso', ru: 'Процесс' },
    { en: 'Sun', es: 'Sol', ru: 'Солнце' },
    { en: 'Tree', es: 'Árbol', ru: 'Дерево' },
    { ru: 'Еда', en: 'Food', es: 'Comida' },
    { en: 'Road', ru: 'Дорога', es: 'Carretera' },
    { ru: 'Окно', en: 'Window', es: 'Ventana' },
    { en: 'Phone', ru: 'Телефон', es: 'Teléfono' },
  ],
}
