import { WordSet } from '@/types'

export const verbs: WordSet = {
  id: 'verbs',
  name: {
    en: 'Verbs',
    es: 'Verbos',
    ru: 'Глаголы',
  },
  words: [
    { es: 'Ser', ru: 'Быть', en: 'To be' },
    { es: 'Tener', ru: 'Иметь', en: 'To have' },
    { en: 'To do', es: 'Hacer', ru: 'Делать' },
    { es: 'Decir', en: 'To say', ru: 'Сказать' },
    { es: 'Ir', ru: 'Идти', en: 'To go' },
    { en: 'To get', ru: 'Получать', es: 'Conseguir' },
    { es: 'Preparar', ru: 'Готовить', en: 'To prepare' },
    { es: 'Saber', ru: 'Знать', en: 'To know' },
    { es: 'Pensar', ru: 'Думать', en: 'To think' },
    { es: 'Tomar', ru: 'Брать', en: 'To take' },
    { es: 'Ver', en: 'To see', ru: 'Видеть' },
    { es: 'Venir', en: 'To come', ru: 'Приходить' },
    { es: 'Querer', ru: 'Хотеть', en: 'To want' },
    { es: 'Usar', en: 'To use', ru: 'Использовать' },
    { en: 'To find', ru: 'Находить', es: 'Encontrar' },
    { es: 'Dar', ru: 'Давать', en: 'To give' },
    { es: 'Contar', en: 'To tell', ru: 'Рассказывать' },
    { en: 'To work', es: 'Trabajar', ru: 'Работать' },
    { es: 'Llamar', en: 'To call', ru: 'Звонить' },
    { en: 'To try', es: 'Intentar', ru: 'Пытаться' },
    { en: 'To ask', es: 'Preguntar', ru: 'Спрашивать' },
    { en: 'To need', es: 'Necesitar', ru: 'Нуждаться' },
    { es: 'Sentir', en: 'To feel', ru: 'Чувствовать' },
    { en: 'To become', es: 'Convertirse', ru: 'Становиться' },
    { es: 'Salir', ru: 'Уходить', en: 'To leave' },
    { es: 'Poner', en: 'To put', ru: 'Класть' },
    { en: 'To mean', ru: 'Значить', es: 'Significar' },
    { en: 'To keep', es: 'Guardar', ru: 'Хранить' },
    { en: 'To allow', es: 'Permitir', ru: 'Разрешать' },
    { es: 'Empezar', en: 'To start', ru: 'Начинать' },
    { en: 'To seem', es: 'Parecer', ru: 'Казаться' },
    { es: 'Ayudar', en: 'To help', ru: 'Помогать' },
    { ru: 'Отвечать', en: 'To answer', es: 'Responder' },
    { es: 'Girar', en: 'To turn', ru: 'Поворачивать' },
    { es: 'Terminar', en: 'To finish', ru: 'Заканчивать' },
    { en: 'To show', es: 'Mostrar', ru: 'Показывать' },
    { es: 'Oír', en: 'To hear', ru: 'Слышать' },
    { es: 'Jugar', ru: 'Играть', en: 'To play' },
    { en: 'To run', es: 'Correr', ru: 'Бежать' },
    { es: 'Mover', en: 'To move', ru: 'Двигаться' },
    { es: 'Gustar', en: 'To like', ru: 'Нравиться' },
    { ru: 'Жить', es: 'Vivir', en: 'To live' },
    { es: 'Creer', ru: 'Верить', en: 'To believe' },
    { en: 'To hold', ru: 'Держать', es: 'Sostener' },
    { es: 'Traer', en: 'To bring', ru: 'Приносить' },
    { ru: 'Писать', en: 'To write', es: 'Escribir' },
    { en: 'To provide', es: 'Proporcionar', ru: 'Предоставлять' },
    { en: 'To sit', ru: 'Сидеть', es: 'Sentarse' },
    { ru: 'Стоять', en: 'To stand', es: 'Estar de pie' },
    { es: 'Perder', ru: 'Терять', en: 'To lose' },
    { es: 'Pagar', en: 'To pay', ru: 'Платить' },
    { en: 'To meet', es: 'Reunirse', ru: 'Встречаться' },
    { es: 'Incluir', ru: 'Включать', en: 'To include' },
    { es: 'Continuar', ru: 'Продолжать', en: 'To continue' },
    { en: 'To set', es: 'Establecer', ru: 'Устанавливать' },
    { ru: 'Учиться', en: 'To learn', es: 'Aprender' },
    { ru: 'Менять', es: 'Cambiar', en: 'To change' },
    { ru: 'Вести', en: 'To lead', es: 'Liderar' },
    { es: 'Entender', ru: 'Понимать', en: 'To understand' },
    { es: 'Mirar', en: 'To watch', ru: 'Смотреть' },
    { es: 'Seguir', en: 'To follow', ru: 'Следовать' },
    { es: 'Parar', en: 'To stop', ru: 'Останавливать' },
    { es: 'Crear', en: 'To create', ru: 'Создавать' },
    { es: 'Hablar', en: 'To speak', ru: 'Говорить' },
    { es: 'Leer', ru: 'Читать', en: 'To read' },
    { en: 'To add', es: 'Añadir', ru: 'Добавлять' },
    { es: 'Gastar', ru: 'Тратить', en: 'To spend' },
    { ru: 'Расти', es: 'Crecer', en: 'To grow' },
    { es: 'Abrir', en: 'To open', ru: 'Открывать' },
    { ru: 'Ходить', en: 'To walk', es: 'Caminar' },
    { es: 'Ganar', en: 'To win', ru: 'Побеждать' },
    { es: 'Ofrecer', en: 'To offer', ru: 'Предлагать' },
    { ru: 'Помнить', es: 'Recordar', en: 'To remember' },
    { es: 'Amar', ru: 'Любить', en: 'To love' },
    { ru: 'Считать', es: 'Considerar', en: 'To consider' },
    { es: 'Aparecer', en: 'To appear', ru: 'Появляться' },
    { en: 'To buy', es: 'Comprar', ru: 'Покупать' },
    { ru: 'Ждать', en: 'To wait', es: 'Esperar' },
    { es: 'Servir', ru: 'Служить', en: 'To serve' },
    { es: 'Morir', en: 'To die', ru: 'Умирать' },
    { es: 'Enviar', en: 'To send', ru: 'Отправлять' },
    { es: 'Vender', en: 'To sell', ru: 'Продавать' },
    { ru: 'Строить', en: 'To build', es: 'Construir' },
    { en: 'To stay', es: 'Quedarse', ru: 'Оставаться' },
    { es: 'Caer', ru: 'Падать', en: 'To fall' },
    { en: 'To cut', es: 'Cortar', ru: 'Резать' },
    { en: 'To reach', es: 'Alcanzar', ru: 'Достигать' },
    { es: 'Matar', en: 'To kill', ru: 'Убивать' },
    { es: 'Salvar', en: 'To save', ru: 'Спасать' },
    { ru: 'Есть', es: 'Comer', en: 'To eat' },
    { ru: 'Пить', es: 'Beber', en: 'To drink' },
    { ru: 'Спать', es: 'Dormir', en: 'To sleep' },
    { ru: 'Водить', en: 'To drive', es: 'Conducir' },
    { es: 'Elegir', ru: 'Выбирать', en: 'To choose' },
    { ru: 'Нести', es: 'Llevar', en: 'To carry' },
    { es: 'Romper', ru: 'Ломать', en: 'To break' },
    { es: 'Limpiar', ru: 'Чистить', en: 'To clean' },
    { es: 'Explicar', ru: 'Объяснять', en: 'To explain' },
    { es: 'Gritar', ru: 'Кричать', en: 'To scream' },
    { ru: 'Мыть', es: 'Lavar', en: 'To wash' },
  ],
}
